### ISSUE TITLE
Go to code location in PDF is broken

### ISSUE THREAD

**Issue by staslev** [overleaf/web#626] opened 2018-02-18 09:52 UTC
The _go to code location in PDF_ (a.k.a. `➡`) feature used to mark the relevant part of the PDF in yellow (relevant being the part corresponding to the location in the code). 
Now however, upon clicking _go to code location in PDF_ **nothing happens**.

Interestingly enough, the other direction, _go to PDF location in code_ (a.k.a  `⬅`), works just fine, and I'm able to right click on the PDF or use the `⬅` arrow to go to the code location from the PDF document.

This was a really nice feature and I would love to see it back.

Love your great platform, keep up the good work!

Edit: I noticed this only happens in some of the projects I'm working on, while in others this functionality continues working as expected.

**Comment by danielbarati** [comment] 2019-06-04 12:51
Wanted to inform you that this is still a problem over a year later. For me at least.

**Comment by DBa2016** [comment] 2019-06-17 11:20
One addition here: it works for from the main file (both directions), however not from the included chapter files.

**Comment by tuterbatuhan** [comment] 2019-07-03 13:19
Present for me as well

**Comment by dtaindjis** [comment] 2019-08-30 07:51
I've the same issue as well, and experience the same behaviour as described by @staslev and @DBa2016 : _Go to PDF location in code_ works from everywhere in the PDF file, opening included chapter files if needed, while _Go to code location in PDF_ works only in the main tex file, and not in the included tex files.

**Comment by yl1991** [comment] 2019-09-14 07:32
same issue here.

**Comment by Irismoon** [comment] 2019-09-28 01:49
exactly same issue as @dtain .

**Comment by aggelos-ioannou** [comment] 2019-10-23 17:29
Exactly the same here. And even in the main file, I just get everything blinking yellow, and not only the line I have selected.

**Comment by AlexTo** [comment] 2019-10-29 05:37
same :)

**Comment by awmann** [comment] 2019-11-11 20:36
same!

**Comment by twoexponents** [comment] 2019-11-13 07:37
Same

**Comment by ShaneKilkelly** [comment] 2019-11-14 10:04
Hi all, just to clarify, is this happening on www.overleaf.com, or only on Community Edition installs?

**Comment by dtain** [comment] 2019-11-14 10:34
> Hi all, just to clarify, is this happening on [www.overleaf.com](http://www.overleaf.com), or only on Community Edition installs?

Hi @ShaneKilkelly ,
At least in my case, this is happening on www.overleaf.com.

**Comment by awmann** [comment] 2019-11-14 11:08
> Hi all, just to clarify, is this happening on [www.overleaf.com](http://www.overleaf.com), or only on Community Edition installs?

overleaf.com

**Comment by ShaneKilkelly** [comment] 2019-11-14 15:20
Thanks! in that case, could y'all send an email to support@overleaf.com, with details of what's happening, so it can be dealt with through our usual support channels?

I'll close this issue for now, and post an update when the problem is resolved.

**Closed** 2019-11-14 15:21 UTC

**Comment by dtain** [comment] 2019-11-15 13:49
> Thanks! in that case, could y'all send an email to [support@overleaf.com](mailto:support@overleaf.com), with details of what's happening, so it can be dealt with through our usual support channels?
> 
> I'll close this issue for now, and post an update when the problem is resolved.

Hi all,

I've just had an exchange with the Overleaf support team, and I was given a fix that worked in my case, so I felt like sharing it here.
In my case, the project on which I've had the issue is a multi-file one, with chapters in separate files, included in the main .tex file using the \include command.

When trying to build a minimum working example project reproducing the issue, I found out that having chapter files on the root level, together with the main file, was not causing the issue: I had it only when putting the chapter files in folders. I was then suspecting the cause to be linked to folder structures.

It turned out that the root cause may be different.
When I was including chapter files, I was used to use the following syntax: `\include{./folder/file}`.
Changing it to `\include{folder/file}`, removing the "./" at the beginning of the path, made the feature "Go to code location in PDF" work perfectly again.

Hope it can help other people with this issue.
And thanks to the Overleaf support team for their very quick feedback.

**Comment by iwadlow** [comment] 2020-01-22 01:30
Hi all, I just found out that if you use \subfile{chapters/section} instead of \include{chapter/section} then you will have this error - switching to \include fixed it for me.

**Comment by trampguy1** [comment] 2020-03-29 23:52
As of today, March 25, 2020, the location finder does not work in either direction. It was working a while ago and then stopped working. I really think you ought to fix this. I spend almost 50 percent of my time trying to find corresponding spots in the PDF to on source code, and it is driving me crazy. This is my first project in Overleaf. There may be easier (working) ways to match up locations but I haven't found them.
If this cannot be fixed, this will probably my last project in Overview, as well as the first.

**Comment by das7pad** [comment] 2020-03-30 08:27
@trampguy1 Hi! Thanks for the report and I am sorry for the bad experience with your first project. Can you please contact support@overleaf.com about this issue?

**Comment by aggelos-ioannou** [comment] 2020-03-30 08:47
Hoping that this might help: This only works if -at least- the main file is
in the top folder and not a subfolder!

**Comment by henrikbrautmeier** [comment] 2020-05-30 10:46
I can confirm that it only works if the main file is not contained in a subfolder. For me, it doesn't matter if other chapters are included in subfolders but the main.tex file should be in the main directory

**Comment by EivindYN** [comment] 2020-11-12 13:47
> 
> 
> > Thanks! in that case, could y'all send an email to [support@overleaf.com](mailto:support@overleaf.com), with details of what's happening, so it can be dealt with through our usual support channels?
> > I'll close this issue for now, and post an update when the problem is resolved.
> 
> Hi all,
> 
> I've just had an exchange with the Overleaf support team, and I was given a fix that worked in my case, so I felt like sharing it here.
> In my case, the project on which I've had the issue is a multi-file one, with chapters in separate files, included in the main .tex file using the \include command.
> 
> When trying to build a minimum working example project reproducing the issue, I found out that having chapter files on the root level, together with the main file, was not causing the issue: I had it only when putting the chapter files in folders. I was then suspecting the cause to be linked to folder structures.
> 
> It turned out that the root cause may be different.
> When I was including chapter files, I was used to use the following syntax: `\include{./folder/file}`.
> Changing it to `\include{folder/file}`, removing the "./" at the beginning of the path, made the feature "Go to code location in PDF" work perfectly again.
> 
> Hope it can help other people with this issue.
> And thanks to the Overleaf support team for their very quick feedback.

This worked for me. Overleaf should fix this. This bug wastes a lot of time as the "Go to code" is such a needed and usefull functionability.

**Comment by MrZMN** [comment] 2021-01-18 14:18
I had this problem before. And I found it was because that I modified the file name (specifically, name of 'xxx.tex'). I changed it back and the double click tool came back.

**Comment by tx3mm** [comment] 2021-02-16 18:40
> > Thanks! in that case, could y'all send an email to [support@overleaf.com](mailto:support@overleaf.com), with details of what's happening, so it can be dealt with through our usual support channels?
> > I'll close this issue for now, and post an update when the problem is resolved.
> 
> Hi all,
> 
> I've just had an exchange with the Overleaf support team, and I was given a fix that worked in my case, so I felt like sharing it here.
> In my case, the project on which I've had the issue is a multi-file one, with chapters in separate files, included in the main .tex file using the \include command.
> 
> When trying to build a minimum working example project reproducing the issue, I found out that having chapter files on the root level, together with the main file, was not causing the issue: I had it only when putting the chapter files in folders. I was then suspecting the cause to be linked to folder structures.
> 
> It turned out that the root cause may be different.
> When I was including chapter files, I was used to use the following syntax: `\include{./folder/file}`.
> Changing it to `\include{folder/file}`, removing the "./" at the beginning of the path, made the feature "Go to code location in PDF" work perfectly again.
> 
> Hope it can help other people with this issue.
> And thanks to the Overleaf support team for their very quick feedback.

Funny enough for me, the solution was exactly the opposite. Only after I added the "./" I was able to make the feature "Go to code location in PDF" work.

**Comment by CymaticsCC** [comment] 2021-07-20 02:32
Hi,
I come across this problem again. Even I am using a example project, it cannot locate the code position in pdf.
I am using a docker version sharelatex 2.7.0.

**Comment by mattrussell2** [comment] 2021-08-05 20:14
After changing files in the code section if you recompile the arrow works.
